baseURL = "https://udl-eps-projectmanagement.github.io/ProjectManagementClasses/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]